name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-validate:
    name: Lint & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

  validate-structure:
    name: Validate Project Structure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check required files
        run: |
          test -f package.json
          test -f README.md
          test -f .env.example
          test -f src/index.js
          test -f src/config/index.js
          test -d src/commands
          test -d src/events
          test -d src/utils
          test -d src/security

      - name: Validate package.json
        run: |
          node -e "const pkg = require('./package.json'); if (!pkg.name || !pkg.version) process.exit(1);"

  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: [lint-and-validate, security-audit, validate-structure]
    if: always()

    steps:
      - name: Check job status
        run: |
          if [ "${{ needs.lint-and-validate.result }}" == "success" ] && \
             [ "${{ needs.validate-structure.result }}" == "success" ]; then
            echo "✅ All checks passed!"
          else
            echo "❌ Some checks failed"
            exit 1
          fi
